from typing import Dict,List,TypedDict,Optional

greetings: List[str] = ["Hi!", "Hello there!", "Hello!", "Greetings, fair yarn worker!"]

unknown_replies: List[str]  = ["I'm not sure what you mean.",
           "I'm sorry, I don't know that.",
           "I'm just a sheep.",
           "I know a lot about other things that aren't that thing.",
           "Sheep don't understand all of the things yet.",
           ":thinking_face:",
           ":confused:",
           ":persevere:"]

AcronymData = TypedDict('AcronymData', {'desc':str, 'url':Optional[str]})

acronyms: Dict[str,AcronymData] = {
    'pat': {'desc': 'pattern', 'url': None},
    'pats': {'desc': 'patterns', 'url': None},
    'patt': {'desc': 'pattern', 'url': None},
    'pm': {'desc': 'place marker', 'url': None},
    'pop': {'desc': 'popcorn', 'url': None},
    'p2tog': {
        'desc': 'purl 2 stitches together',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/decreases/k2tog'},
    'psso': {
        'desc': 'pass slipped stitch over',
        'url': 'http://newstitchaday.com/pass-slipped-stitch-over-decrease/'},
    'pwise': {'desc': 'purlwise', 'url': None},
    'beg': {'desc': 'begin/beginning', 'url': None},
    'rem': {'desc': 'remain/remaining', 'url': None},
    'bet': {'desc': 'between', 'url': None},
    'rep': {'desc': 'repeat(s)', 'url': None},
    'bo': {
        'desc': 'bind off',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/learn_to_knit/binding_off'},
    'ca': {'desc': 'color A', 'url': None},
    'rh': {'desc': 'right hand', 'url': None},
    'cb': {'desc': 'color B ', 'url': None},
    'rnd': {'desc': 'round', 'url': None},
    'rnds': {'desc': 'rounds', 'url': None},
    'cc': {'desc': 'contrasting color ', 'url': None},
    'rs': {'desc': 'right side ', 'url': None},
    'sk': {'desc': 'skip', 'url': None},
    'cn': {'desc': 'cable needle', 'url': None},
    'skp': {
        'desc': 'slip, knit, pass stitch over; one stitch decreased',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/decreases/skp'},
    'co': {
        'desc': 'cast on',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/learn_to_knit/first_stitches'},
    'sk2p': {
        'desc': 'slip 1, knit 2 together, pass slip stitch over the knit 2 together; 2 stitches have been decreased',
        'url': 'http://newstitchaday.com/slip-knit-two-pass-double-decrease/'},
    'cont': {'desc': 'continue ', 'url': None},
    'dec': {
        'desc': 'decrease/decreases/decreasing',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/decreases'},
    'sl1k': {'desc': 'slip 1 knitwise', 'url': 'https://www.youtube.com/watch?v=_Wh8kmdqfcw'},
    'dpn': {'desc': 'double pointed needle(s)', 'url': None},
    'sl1p': {'desc': 'slip 1 purlwise', 'url': 'https://www.youtube.com/watch?v=6EX_KbVknP0'},
    'fl': {'desc': 'front loop(s)', 'url': None},
    'sl': {'desc': 'st slip stitch(es)', 'url': None},
    'foll': {'desc': 'follow/follows/following', 'url': None},
    'ss': {'desc': 'slip stitch', 'url': None},
    'ssk': {
        'desc': 'slip, slip, knit these 2 stiches together; decrease',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/decreases/ssk'},
    'inc': {
        'desc': 'increase/increases/increasing',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/increases'},
    'sssk': {
        'desc': 'slip, slip, slip, knit 3 stitches together',
        'url': 'http://newstitchaday.com/slip-slip-slip-knit-double-decrease/'},
    'k': {'desc': 'knit', 'url': 'http://www.vogueknitting.com/pattern_help/how-to/learn_to_knit/the_knit_stitch'},
    'kfb': {'desc': 'knit front and back', 'url': 'http://newstitchaday.com/knit-front-and-back-increase-kfb/'},
    'st': {'desc': 'stitch', 'url': None},
    'sts': {'desc': 'stitches', 'url': None},
    'k2tog': {
        'desc': 'knit 2 stitches together',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/decreases/k2tog'},
    'kwise': {'desc': 'knitwise', 'url': None},
    'tbl': {'desc': 'through back loop', 'url': 'http://newstitchaday.com/k-tbl-knit-through-back-loop/'},
    'lh': {'desc': 'left hand', 'url': None},
    'tog': {'desc': 'together', 'url': None},
    'lp': {'desc': 'loop', 'url': None},
    'lps': {'desc': 'loops', 'url': None},
    'ws': {'desc': 'wrong side', 'url': None},
    'wyib': {'desc': 'with yarn in back', 'url': None},
    'm1': {
        'desc': 'make one stitch',
        'url': 'http://www.vogueknitting.com/pattern_help/how-to/beyond_the_basics/increases/make_one_increase'},
    'm1r': {
        'desc': 'make one stitch right',
        'url': 'http://newstitchaday.com/m1r-make-one-right-increase-knitting/'},
    'm1l': {
        'desc': 'make one stitch left',
        'url': 'http://newstitchaday.com/m1l-make-one-left-increase-knitting/'},
    'wyif': {'desc': 'with yarn in front', 'url': None},
    'mc': {'desc': 'main color', 'url': None},
    'yfwd': {'desc': 'yarn forward', 'url': None},
    'yo': {'desc': 'yarn over', 'url': None},
    'oz': {'desc': 'ounce(s)', 'url': None},
    'yrn': {'desc': 'yarn around needle', 'url': None},
    'p': {'desc': 'purl', 'url': 'http://www.vogueknitting.com/pattern_help/how-to/learn_to_knit/the_purl_stitch'},
    'yon': {'desc': 'yarn over needle', 'url': None}}

yarn_weights: Dict[str,dict] = {
    'cobweb':      {'ply': 1, 'wpi': '??', 'gauge': '??', 'number': 0},
    'lace':        {'ply': 2, 'wpi': '??', 'gauge': '32-34', 'number': 0},
    'light fingering': {'ply': 3, 'wpi': '??', 'gauge': '32', 'number': 0},
    'fingering':       {'ply': 4, 'wpi': '14', 'gauge': '28', 'number': 1},
    'sport':       {'ply': 5, 'wpi': '12', 'gauge': '24-26', 'number': 2},
    'dk':          {'ply': 8, 'wpi': '11', 'gauge': '22', 'number': 3},
    'worsted':     {'ply': 10, 'wpi': '9', 'gauge': '20', 'number': 4},
    'aran':        {'ply': 10, 'wpi': '8', 'gauge': '18', 'number': 4},
    'bulky':       {'ply': 12, 'wpi': '7', 'gauge': '14-15', 'number': 5},
    'super bulky':     {'ply': '??', 'wpi': '5-6', 'gauge': '7-12', 'number': 6},
    'jumbo':       {'ply': '??', 'wpi': '0-4', 'gauge': '0-6', 'number': 7}
    }

yarn_fibers: List[str] = [
    'acrylic',
    'alpaca',
    'angora',
    'bamboo',
    'bison',
    'camel',
    'cashmere',
    'cotton',
    'hemp',
    'linen',
    'llama',
    'merino',
    'metallic',
    'microfiber',
    'mohair',
    'nylon',
    'other',
    'plant-fiber',
    'polyester',
    'qiviut',
    'rayon',
    'silk',
    'soy',
    'tencel',
    'wool',
    'yak'
    ]

needles_by_us: Dict[str,dict] = {
    '0': {'metric': '2.0', 'uk': '14', 'crochet': '-'},
    '1': {'metric': '2.25', 'uk': '13', 'crochet': 'B'},
    '2': {'metric': '2.75', 'uk': '12', 'crochet': 'C'},
    '3': {'metric': '3.0/3.25', 'uk': '10/11', 'crochet': 'D'},
    '4': {'metric': '3.5', 'uk': '9', 'crochet': 'E'},
    '5': {'metric': '3.75', 'uk': '9', 'crochet': 'F'},
    '6': {'metric': '4.0', 'uk': '8', 'crochet': 'G'},
    '7': {'metric': '4.5', 'uk': '7', 'crochet': '-'},
    '8': {'metric': '5.0', 'uk': '6', 'crochet': 'H'},
    '9': {'metric': '5.5', 'uk': '5', 'crochet': 'I'},
    '10': {'metric': '6.0', 'uk': '4', 'crochet': 'J'},
    '10.5': {'metric': '6.5', 'uk': '3', 'crochet': 'K'},
    '10 1/2': {'metric': '6.5', 'uk': '3', 'crochet': 'K'},
    '11': {'metric': '8.0', 'uk': '0', 'crochet': 'L'},
    '13': {'metric': '9.0', 'uk': '00', 'crochet': '-'},
    '15': {'metric': '10.0', 'uk': '000', 'crochet': '-'},
    '17': {'metric': '12.0', 'uk': '-', 'crochet': '-'},
    '19': {'metric': '15.0', 'uk': '-', 'crochet': '-'},
    '35': {'metric': '20.0', 'uk': '-', 'crochet': '-'},
    '50': {'metric': '50.0', 'uk': '-', 'crochet': '-'},
    }
needles_by_metric: Dict[str,dict] = {
    '2.00': {'us': '0', 'uk': '14', 'crochet': '-'},
    '2.25': {'us': '1', 'uk': '13', 'crochet': 'B'},
    '2.50': {'us': '-', 'uk': '12', 'crochet': '-'},
    '2.75': {'us': '2', 'uk': '12', 'crochet': 'C'},
    '3.00': {'us': '3', 'uk': '11', 'crochet': '-'},
    '3.25': {'us': '3', 'uk': '10', 'crochet': 'D'},
    '3.50': {'us': '4', 'uk': '9', 'crochet': 'E'},
    '3.75': {'us': '5', 'uk': '9', 'crochet': 'F'},
    '4.00': {'us': '6', 'uk': '8', 'crochet': 'G'},
    '4.50': {'us': '7', 'uk': '7', 'crochet': '-'},
    '5.00': {'us': '8', 'uk': '6', 'crochet': 'H'},
    '5.50': {'us': '9', 'uk': '5', 'crochet': 'I'},
    '6.00': {'us': '10', 'uk': '4', 'crochet': 'J'},
    '6.50': {'us': '10.5', 'uk': '3', 'crochet': 'K'},
    '7.00': {'us': '-', 'uk': '2', 'crochet': '-'},
    '7.50': {'us': '-', 'uk': '1', 'crochet': '-'},
    '8.00': {'us': '11', 'uk': '0', 'crochet': 'L'},
    '9.00': {'us': '13', 'uk': '00', 'crochet': '-'},
    '10.00': {'us': '15', 'uk': '000', 'crochet': '-'},
    '12.00': {'us': '17', 'uk': '-', 'crochet': '-'},
    '15.00': {'us': '19', 'uk': '-', 'crochet': '-'},
    '20.00': {'us': '35', 'uk': '-', 'crochet': '-'},
    '50.00': {'us': '50', 'uk': '-', 'crochet': '-'},
    }
needles_by_crochet: Dict[str,dict] = {
    'B': {'us': '1', 'uk': '13', 'metric': '2.25'},
    'C': {'us': '2', 'uk': '12', 'metric': '2.75'},
    'D': {'us': '3', 'uk': '10', 'metric': '3.25'},
    'E': {'us': '4', 'uk': '9', 'metric': '3.5'},
    'F': {'us': '5', 'uk': '9', 'metric': '3.75'},
    'G': {'us': '6', 'uk': '8', 'metric': '4.0'},
    'H': {'us': '8', 'uk': '6', 'metric': '5.0'},
    'I': {'us': '9', 'uk': '5', 'metric': '5.5'},
    'J': {'us': '10', 'uk': '4', 'metric': '6.0'},
    'K': {'us': '10.5', 'uk': '3', 'metric': '6.5'},
    'L': {'us': '11', 'uk': '0', 'metric': '8.0'}
    }
needles_by_uk: Dict[str,dict] = {
    '14': {'us': '0', 'crochet': '-', 'metric': '2.0'},
    '13': {'us': '1', 'crochet': 'B', 'metric': '2.25'},
    '12': {'us': '2', 'crochet': 'C', 'metric': '2.5/2.75'},
    '11': {'us': '3', 'crochet': '-', 'metric': '3.0'},
    '10': {'us': '3', 'crochet': 'D', 'metric': '3.25'},
    '9': {'us': '4/5', 'crochet': 'E/F', 'metric': '3.5/3.75'},
    '8': {'us': '6', 'crochet': 'G', 'metric': '4.0'},
    '7': {'us': '7', 'crochet': '-', 'metric': '4.5'},
    '6': {'us': '8', 'crochet': 'H', 'metric': '5.0'},
    '5': {'us': '9', 'crochet': 'I', 'metric': '5.5'},
    '4': {'us': '10', 'crochet': 'J', 'metric': '6.0'},
    '3': {'us': '10.5', 'crochet': 'K', 'metric': '6.5'},
    '2': {'us': '-', 'crochet': '-', 'metric': '7.0'},
    '1': {'us': '-', 'crochet': '-', 'metric': '7.5'},
    '0': {'us': '11', 'crochet': 'L', 'metric': '8.0'},
    '00': {'us': '13', 'crochet': '-', 'metric': '9.0'},
    '000': {'us': '15', 'crochet': '-', 'metric': '10.0'},
    }

jokes: List[str] = [
    "Why did the pig farmer give up knitting?\n\nHe didn't want to cast his purls before swine.",
    "Did you hear what happened to the cat who ate a ball of yarn?\n\nShe had mittens.",
    "So this lady was driving down the highway crocheting as she drove. A highway patrolman noticed her and began pursuit. He drove up next to her car, rolled down his window and said, 'Pull over!' She replied, 'No, it's a scarf!'",
    "How do you make knitted jewelry?\n\nWith purls.",
    "Why are Christmas trees bad at knitting?\n\nBecause they keep dropping their needles",
    "What did the knitted cap say to the afghan?\n\nYou stay here, I'll go on a head."]

